name: fresh_home_staff
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.11.0


dependencies:
  flutter:
    sdk: flutter

  # ---------------------------------------------------------
  # الحزم المحلية (Local Packages)
  # ---------------------------------------------------------
  shared:
    path: ../../packages/shared
  shared_features:
    path: ../../packages/shared_features
  # ---------------------------------------------------------
  # تم إضافة equatable لحل مشاكل التبعيات
  # ---------------------------------------------------------
  equatable: ^2.0.8

  # ---------------------------------------------------------
  # الملاحة وإدارة الحالة (Navigation & DI)
  # ---------------------------------------------------------
  flutter_bloc: ^9.1.1
  go_router: ^17.1.0
  get_it: ^9.2.0
  intl: ^0.20.2
  fpdart: ^1.2.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.0

  # ---------------------------------------------------------
  # فيربيز وخدمات الإشعارات (Firebase & FCM)
  # ---------------------------------------------------------
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^17.2.0

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  supabase_flutter: ^2.8.1
  awesome_dialog: ^3.3.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "../../packages/shared/assets/core/images/app_icon_staff.png"
  adaptive_icon_background: "#EEF2F6"
  adaptive_icon_foreground: "../../packages/shared/assets/core/images/app_icon_staff.png"
