-- ==============================================================================
-- Migration: 98_address_v2_reference_tables.sql
-- Description: Phase 4.1 Production-Grade Reference Tables & Hierarchical Integrity
-- Author: Principal Backend & Database Architect
-- Spec Reference: docs/address_system_v2_specification.md Section 8 & 9
-- ==============================================================================

BEGIN;

-- 1. CREATE GOVERNORATES REFERENCE TABLE
CREATE TABLE IF NOT EXISTS public.governorates (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ar TEXT NOT NULL,
    name_en TEXT NOT NULL,
    code TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_governorates_code UNIQUE (code),
    CONSTRAINT uq_governorates_name_ar UNIQUE (name_ar),
    CONSTRAINT uq_governorates_name_en UNIQUE (name_en)
);

-- 2. CREATE CITIES REFERENCE TABLE WITH COMPOSITE UNIQUE KEY FOR HIERARCHY
CREATE TABLE IF NOT EXISTS public.cities (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    governorate_id INT NOT NULL REFERENCES public.governorates(id) ON DELETE RESTRICT,
    name_ar TEXT NOT NULL,
    name_en TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_cities_governorate_name_ar UNIQUE (governorate_id, name_ar),
    CONSTRAINT uq_cities_governorate_name_en UNIQUE (governorate_id, name_en),
    CONSTRAINT uq_cities_id_governorate_id UNIQUE (id, governorate_id)
);

-- 3. CREATE DISTRICTS REFERENCE TABLE WITH COMPOSITE UNIQUE KEY FOR HIERARCHY
CREATE TABLE IF NOT EXISTS public.districts (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id INT NOT NULL REFERENCES public.cities(id) ON DELETE RESTRICT,
    name_ar TEXT NOT NULL,
    name_en TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    sort_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_districts_city_name_ar UNIQUE (city_id, name_ar),
    CONSTRAINT uq_districts_city_name_en UNIQUE (city_id, name_en),
    CONSTRAINT uq_districts_id_city_id UNIQUE (id, city_id)
);

-- 4. UPDATED_AT TRIGGER FUNCTION FOR REFERENCE TABLES
CREATE OR REPLACE FUNCTION public.fn_update_ref_tables_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_governorates_updated_at ON public.governorates;
CREATE TRIGGER trg_governorates_updated_at BEFORE UPDATE ON public.governorates FOR EACH ROW EXECUTE FUNCTION public.fn_update_ref_tables_updated_at();

DROP TRIGGER IF EXISTS trg_cities_updated_at ON public.cities;
CREATE TRIGGER trg_cities_updated_at BEFORE UPDATE ON public.cities FOR EACH ROW EXECUTE FUNCTION public.fn_update_ref_tables_updated_at();

DROP TRIGGER IF EXISTS trg_districts_updated_at ON public.districts;
CREATE TRIGGER trg_districts_updated_at BEFORE UPDATE ON public.districts FOR EACH ROW EXECUTE FUNCTION public.fn_update_ref_tables_updated_at();

-- 5. INSERT PRODUCTION-GRADE BILINGUAL SEED DATA (CAIRO & GIZA REAL GEOGRAPHY ONLY)

-- Governorates
INSERT INTO public.governorates (id, name_ar, name_en, code, is_active, sort_order)
OVERRIDING SYSTEM VALUE
VALUES 
    (1, 'القاهرة', 'Cairo', 'CAI', true, 1),
    (2, 'الجيزة', 'Giza', 'GIZ', true, 2)
ON CONFLICT (id) DO UPDATE SET 
    name_ar = EXCLUDED.name_ar, 
    name_en = EXCLUDED.name_en, 
    code = EXCLUDED.code;

-- Cities under Cairo (governorate_id = 1)
INSERT INTO public.cities (id, governorate_id, name_ar, name_en, is_active, sort_order)
OVERRIDING SYSTEM VALUE
VALUES 
    (101, 1, 'الزمالك', 'Zamalek', true, 1),
    (102, 1, 'جاردن سيتي', 'Garden City', true, 2),
    (103, 1, 'المعادي', 'Maadi', true, 3),
    (104, 1, 'مصر الجديدة', 'Heliopolis', true, 4),
    (105, 1, 'التجمع الخامس', 'Fifth Settlement', true, 5),
    (106, 1, 'القاهرة الجديدة', 'New Cairo', true, 6),
    (107, 1, 'الرحاب', 'Rehab', true, 7),
    (108, 1, 'مدينتي', 'Madinaty', true, 8),
    (109, 1, 'مدينة نصر', 'Nasr City', true, 9),
    (110, 1, 'المقطم', 'Mokattam', true, 10),
    (111, 1, 'الشروق', 'Shorouk', true, 11),
-- Cities under Giza (governorate_id = 2)
    (201, 2, 'الشيخ زايد', 'Zayed', true, 1),
    (202, 2, '6 أكتوبر', '6th of October', true, 2),
    (203, 2, 'المهندسين', 'Mohandessin', true, 3),
    (204, 2, 'الدقي', 'Dokki', true, 4),
    (205, 2, 'العجوزة', 'Agouza', true, 5),
    (206, 2, 'حدائق الأهرام', 'Hadayek Al Ahram', true, 6),
    (207, 2, 'الهرم', 'Haram', true, 7),
    (208, 2, 'فيصل', 'Faisal', true, 8),
    (209, 2, 'إمبابة', 'Imbaba', true, 9)
ON CONFLICT (id) DO UPDATE SET 
    governorate_id = EXCLUDED.governorate_id,
    name_ar = EXCLUDED.name_ar,
    name_en = EXCLUDED.name_en;

-- Real Districts under Representative Cities
INSERT INTO public.districts (id, city_id, name_ar, name_en, is_active, sort_order)
OVERRIDING SYSTEM VALUE
VALUES 
    -- Fifth Settlement (city_id = 105)
    (1051, 105, 'الحي الأول', 'First District', true, 1),
    (1052, 105, 'الحي الثاني', 'Second District', true, 2),
    (1053, 105, 'الحي الثالث', 'Third District', true, 3),
    (1054, 105, 'الحي الرابع', 'Fourth District', true, 4),
    (1055, 105, 'الحي الخامس', 'Fifth District', true, 5),
    (1056, 105, 'حي الشويفات', 'Choueifat District', true, 6),
    (1057, 105, 'حي الدبلوماسيين', 'Diplomat District', true, 7),
    (1058, 105, 'حي النرجس', 'Narges District', true, 8),
    (1059, 105, 'حي الياسمين', 'Jasmine District', true, 9),
    (1060, 105, 'حي البنفسج', 'Violet District', true, 10),
    -- New Cairo (city_id = 106)
    (1061, 106, 'التجمع الأول', 'First Settlement', true, 1),
    (1062, 106, 'التجمع الثالث', 'Third Settlement', true, 2),
    (1063, 106, 'حي اللوتس', 'Lotus District', true, 3),
    (1064, 106, 'حي الأندلس', 'Andalus District', true, 4),
    -- Zayed (city_id = 201)
    (2011, 201, 'الحي الأول', 'First District', true, 1),
    (2012, 201, 'الحي الثاني', 'Second District', true, 2),
    (2013, 201, 'الحي السابع', 'Seventh District', true, 3),
    (2014, 201, 'الحي الثامن', 'Eighth District', true, 4),
    (2015, 201, 'الحي الحادي عشر', 'Eleventh District', true, 5),
    (2016, 201, 'زايد ديونز', 'Zayed Dunes', true, 6),
    (2017, 201, 'بيفرلي هيلز', 'Beverly Hills', true, 7),
    -- 6th of October (city_id = 202)
    (2021, 202, 'الحي الأول', 'First District', true, 1),
    (2022, 202, 'الحي الثاني', 'Second District', true, 2),
    (2023, 202, 'الحي الثالث', 'Third District', true, 3),
    (2024, 202, 'الحي الرابع', 'Fourth District', true, 4),
    (2025, 202, 'الحي الخامس', 'Fifth District', true, 5),
    (2026, 202, 'الحي السادس', 'Sixth District', true, 6),
    (2027, 202, 'المنطقة السياحية', 'Tourism Area', true, 7)
ON CONFLICT (id) DO UPDATE SET 
    city_id = EXCLUDED.city_id,
    name_ar = EXCLUDED.name_ar,
    name_en = EXCLUDED.name_en;

-- RESET IDENTITY SEQUENCES FOR PRECISE IDENTITY GENERATION
SELECT setval(pg_get_serial_sequence('public.governorates', 'id'), (SELECT MAX(id) FROM public.governorates));
SELECT setval(pg_get_serial_sequence('public.cities', 'id'), (SELECT MAX(id) FROM public.cities));
SELECT setval(pg_get_serial_sequence('public.districts', 'id'), (SELECT MAX(id) FROM public.districts));

-- 6. INTEGRATE REFERENCE IDS WITH PUBLIC.USER_ADDRESSES
ALTER TABLE public.user_addresses 
  ADD COLUMN IF NOT EXISTS governorate_id INT REFERENCES public.governorates(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS city_id INT REFERENCES public.cities(id) ON DELETE RESTRICT,
  ADD COLUMN IF NOT EXISTS district_id INT REFERENCES public.districts(id) ON DELETE RESTRICT;

-- DECLARATIVE COMPOSITE FOREIGN KEYS ENFORCING STRICT HIERARCHICAL INTEGRITY!
-- Guarantees at database level that city_id belongs to governorate_id and district_id belongs to city_id!
ALTER TABLE public.user_addresses DROP CONSTRAINT IF EXISTS fk_user_addresses_city_governorate_hierarchy;
ALTER TABLE public.user_addresses 
  ADD CONSTRAINT fk_user_addresses_city_governorate_hierarchy 
  FOREIGN KEY (city_id, governorate_id) 
  REFERENCES public.cities(id, governorate_id) 
  ON DELETE RESTRICT;

ALTER TABLE public.user_addresses DROP CONSTRAINT IF EXISTS fk_user_addresses_district_city_hierarchy;
ALTER TABLE public.user_addresses 
  ADD CONSTRAINT fk_user_addresses_district_city_hierarchy 
  FOREIGN KEY (district_id, city_id) 
  REFERENCES public.districts(id, city_id) 
  ON DELETE RESTRICT;

-- 7. PROPERTY TYPE ENUM & PAIRED GPS COORDINATES CHECK CONSTRAINTS
ALTER TABLE public.user_addresses DROP CONSTRAINT IF EXISTS chk_property_type_enum;
ALTER TABLE public.user_addresses ADD CONSTRAINT chk_property_type_enum 
    CHECK (property_type IS NULL OR property_type IN ('residential', 'office', 'commercial', 'landmark'));

ALTER TABLE public.user_addresses DROP CONSTRAINT IF EXISTS chk_paired_coordinates;
ALTER TABLE public.user_addresses ADD CONSTRAINT chk_paired_coordinates 
    CHECK ((latitude IS NULL AND longitude IS NULL) OR (latitude IS NOT NULL AND longitude IS NOT NULL));

-- 8. INDEXING FOR HIGH-PERFORMANCE HIERARCHICAL QUERIES
CREATE INDEX IF NOT EXISTS idx_cities_governorate_id ON public.cities(governorate_id) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_districts_city_id ON public.districts(city_id) WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_user_addresses_governorate_id ON public.user_addresses(governorate_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_user_addresses_city_id ON public.user_addresses(city_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_user_addresses_district_id ON public.user_addresses(district_id) WHERE deleted_at IS NULL;

-- 9. ROW LEVEL SECURITY (RLS) POLICIES FOR REFERENCE TABLES
ALTER TABLE public.governorates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.districts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public and authenticated select on governorates" ON public.governorates;
CREATE POLICY "Allow public and authenticated select on governorates" ON public.governorates FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public and authenticated select on cities" ON public.cities;
CREATE POLICY "Allow public and authenticated select on cities" ON public.cities FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public and authenticated select on districts" ON public.districts;
CREATE POLICY "Allow public and authenticated select on districts" ON public.districts FOR SELECT USING (true);

COMMIT;
