import 'package:flutter/material.dart';
import 'package:fpdart/fpdart.dart';
import 'package:shared_features/shared_features.dart';
import 'package:supabase_flutter/supabase_flutter.dart' hide User;
import 'package:shared/core/error/failures.dart';
import 'package:shared/core/error/error_mapper.dart';
import 'package:shared/core/error/exceptions.dart';
import 'package:shared/domain/user/entities/user/user.dart';
import 'package:shared/domain/user/enums/user_role.dart';
import 'package:shared/domain/user/enums/user_status.dart';
import 'package:shared/data/user/datasources/user_remote_datasource.dart';
import 'package:shared/data/user/models/remote/user_remote_model.dart';
import 'package:shared/data/user/mappers/user_mapper.dart';


class UserRepositoryImpl implements UserRepositories {
  final AuthRemoteDataSource authDataSource;
  final UserRemoteDataSource userRemoteDataSource;
  final AuthLocalDataSource localDataSource;
  final UserRole defaultRole;

  UserRepositoryImpl({
    required this.authDataSource,
    required this.userRemoteDataSource,
    required this.localDataSource,
    required this.defaultRole,
  });

  @override
  Future<Either<Failure, User>> signUp(
    String email,
    String password,
    String firstName,
    String lastName,
  ) async {
    try {
      final response = await authDataSource.signUp(
        email: email,
        password: password,
        data: {
          'first_name': firstName,
          'last_name': lastName,
          'app_type': defaultRole.name,
        },
      );

      if (response.user != null) {
        // Profile is created by DB trigger.
        // We'll return a partial user object for now, or fetch from DB if needed.
        // For Clean Architecture consistency, we'll return what we have.
        final returnedUser = response.user;
        if (returnedUser != null) {
          // The profile is created by a DB trigger, so we don't need to insert it here.
          // We just need to construct the User entity to return.
          final user = User(
            customId: 0, // Generated by DB trigger, might need sync
            uid: returnedUser.id,
            firstName: firstName,
            lastName: lastName,
            email: email,
            accountStatus: UserStatus.active,
            gender: 'unspecified',
            avatarUrl: returnedUser.userMetadata?['avatar_url']?.toString(),
            roles: [defaultRole],
            createdAt: DateTime.now(),
            updatedAt: DateTime.now(),
          );
          return Right(user);
        }
      }
      return Left(UnknownFailure(message: 'User creation failed'));
    } on AppException catch (e) {
      return Left(ErrorMapper.mapExternalServiceError(e));
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, void>> signIn(String email, String password) async {
    try {
      final response = await authDataSource.signIn(email, password);
      if (response.user == null) {
        return Left(
          AuthFailure(
            message: 'Invalid credentials',
            code: 'invalid_credentials',
          ),
        );
      }

      // Fetch user profile from Supabase profiles table
      final userRemoteModel = await userRemoteDataSource.getUserById(
        response.user!.id,
      );

      // Cache the user locally if profile exists
      if (userRemoteModel != null) {
        await localDataSource.cacheUser(UserMapper.remoteToHive(userRemoteModel));
      }

      return const Right(null);
    } on AppException catch (e) {
      return Left(ErrorMapper.mapExternalServiceError(e));
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, void>> signOut() async {
    try {
      await Future.wait([
        authDataSource.signOut(),
        localDataSource.clearCache(),
      ]);
      return const Right(null);
    } on AppException catch (e) {
      return Left(ErrorMapper.mapExternalServiceError(e));
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, void>> resendVerificationCode(
    String email,
    String password,
  ) async {
    // Supabase allows simple resend via auth.resend
    return Left(UnknownFailure(message: 'Use Supabase resend instead'));
  }

  @override
  Future<Either<Failure, void>> resetPassword(String email, {required String redirectTo}) async {
    try {
      await authDataSource.sendPasswordResetEmail(email, redirectTo: redirectTo);
      return const Right(null);
    } on AppException catch (e) {
      return Left(ErrorMapper.mapExternalServiceError(e));
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, void>> signInWithGoogle({required String redirectTo}) async {
    try {
      await authDataSource.signInWithGoogle(redirectTo: redirectTo);
      return const Right(null);
    } on AppException catch (e) {
      return Left(ErrorMapper.mapExternalServiceError(e));
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, void>> ensureRole(String roleName) async {
    try {
      await authDataSource.assignRole(roleName);
      return const Right(null);
    } on AppException catch (e) {
      return Left(ErrorMapper.mapExternalServiceError(e));
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, bool>> verifyRole(String roleName) async {
    try {
      final currentUser = Supabase.instance.client.auth.currentUser;
      if (currentUser == null) return const Right(false);

      // Fetch user profile from Supabase profiles table
      UserRemoteModel? userProfileOriginal = await userRemoteDataSource.getUserById(currentUser.id);

      if (userProfileOriginal == null) {
        debugPrint('⚠️ [UserRepositoryImpl] No profile found for user ${currentUser.id}');
        return const Right(false);
      }

      UserRemoteModel finalProfile = userProfileOriginal;

      // 🛠️ Profile Sync Logic: Fix "user" default name from Google/OAuth
      final Map<String, dynamic>? metadata = currentUser.userMetadata;
      if (metadata != null &&
          (finalProfile.firstName.toLowerCase() == 'user' || finalProfile.firstName.isEmpty)) {
        String? firstName = metadata['given_name']?.toString();
        String? lastName = metadata['family_name']?.toString();
        String? fullName = metadata['full_name']?.toString() ?? metadata['name']?.toString();
        String? avatarUrl = metadata['avatar_url']?.toString() ?? metadata['picture']?.toString();

        if (firstName == null && fullName != null) {
          final parts = fullName.trim().split(' ');
          firstName = parts.first;
          lastName = parts.length > 1 ? parts.sublist(1).join(' ') : '';
        }

        if (firstName != null && firstName.isNotEmpty) {
          final updatedModel = finalProfile.copyWith(
            firstName: firstName,
            lastName: lastName ?? '',
            avatarUrl: avatarUrl ?? finalProfile.avatarUrl,
          );

          debugPrint('🔄 [UserRepositoryImpl] Syncing profile from metadata: $firstName $lastName');
          try {
            await userRemoteDataSource.updateUser(user: updatedModel);
            finalProfile = updatedModel; // Use updated model for role check and caching
          } catch (e) {
            debugPrint('⚠️ [UserRepositoryImpl] Profile sync failed: $e');
          }
        }
      }

      // Check if the user has the required role
      final List<UserRole> rolesEnums = finalProfile.roles;
      debugPrint('🔑 [UserRepositoryImpl] User roles found: ${rolesEnums.map((r) => r.name).toList()}');
      debugPrint('🎯 [UserRepositoryImpl] Required role: $roleName');
      
      bool hasRole = rolesEnums.any((r) => r.name.toLowerCase() == roleName.toLowerCase());

      // Fallback: Check Supabase Auth app_metadata
      if (!hasRole && currentUser.appMetadata.containsKey('roles')) {
        final authRoles = currentUser.appMetadata['roles'];
        debugPrint('🔍 [UserRepositoryImpl] Checking app_metadata roles fallback: $authRoles');
        if (authRoles is List) {
          hasRole = authRoles.any((r) => r.toString().toLowerCase() == roleName.toLowerCase());
        } else if (authRoles is String) {
          hasRole = authRoles.toLowerCase() == roleName.toLowerCase();
        }
      }

      debugPrint('✅ [UserRepositoryImpl] Final hasRole result: $hasRole');

      // Cache the updated user profile locally
      try {
        await localDataSource.cacheUser(UserMapper.remoteToHive(finalProfile));
      } catch (e) {
        debugPrint('⚠️ [UserRepositoryImpl] Local caching failed: $e');
      }

      return Right(hasRole);
    } on AppException catch (e) {
      return Left(ErrorMapper.mapExternalServiceError(e));
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<Either<Failure, void>> updatePassword(String newPassword) async {
    try {
      await authDataSource.updatePassword(newPassword);
      return const Right(null);
    } on AppException catch (e) {
      return Left(ErrorMapper.mapExternalServiceError(e));
    } catch (e) {
      return Left(UnknownFailure(message: e.toString()));
    }
  }

  @override
  Future<User?> getCurrentUser() async {
    try {
      final currentUser = Supabase.instance.client.auth.currentUser;
      if (currentUser == null) return null;

      final userProfile = await userRemoteDataSource.getUserById(currentUser.id);
      if (userProfile == null) return null;

      return UserMapper.remoteToEntity(userProfile);
    } catch (e) {
      debugPrint('❌ [UserRepositoryImpl] getCurrentUser failed: $e');
      return null;
    }
  }
}
